app/blueprints/electricity/views.py
from flask import Blueprint, render_template, request
from flask_security import login_required
import sqlite3
from datetime import datetime
import time
import random
from app.models import Light_sturf, Light_sturf_update
from app import db 


electricity = Blueprint('electricity', __name__, 
    static_folder='static', static_url_path = '/static')



@electricity.route('/')
@login_required 
def where():
    return render_template("electricity/where.html")


#this route saves all date gotten as query parameters
@electricity.route('/BtfT2GB2h9s4kP_cjZdqkSv5Bps/api-save',methods=['GET'])
def api_save():
    #this function populates the light_sturf table
    def Light_list():
        location = request.args.get('location',  type = str)
        state = request.args.get('state',  type = str) 


        first = Light_sturf(
                        location = location,
                        state = state
                        )


        db.session.add(first)
        db.session.commit()


    #this function updates the light_sturf table which has only a single row
    def Light_update():
        
        location = request.args.get('location',  type = str)
        state = request.args.get('state',  type = str) 

        Light_update = Light_sturf_update.query.filter_by(location = location).first_or_404()

        Light_update.location = location
        Light_update.state = state


       
        db.session.commit()


 
    Light_list()
    Light_update()

    return render_template("electricity/testing.html", location = request.args.get('location',  type = str), state = request.args.get('state',  type = str))
    


# @electricity.route('/first/api-save',methods=['GET'])
# def api_save():
#     location = request.args.get('location',  type = str)
#     status = request.args.get('status',  type = str) 


#     Light_sturf.location = location
#     Light_sturf.status = status


#     light_sturf = Light_sturf(
#                     image_file = filename,
#                     title = title, 
#                     content =  content, 
#                     author = current_user)

 

#     return render_template("electricity/testing.html", location = location, status = status)



@electricity.route('/campus',methods=['GET'])
@login_required  
def campus():
    light = Light_sturf_update.query.filter_by(location = 'campus').first_or_404()
    pic = 'static/lightbulb.gif'
    color = "#79ff4d"
    status = "status"
    report = "report"
    t1 = "t1"
    t2 = "t2"
    title = "Campus"

    success_report = ['Cheers! the power has been restored','Hurray! there is power off campus',
        'The power is back!',
        'The power supply has been restored','The electricity is back!','Homes off campus are shining bright! '
        ]

    failure_report = ['oops! no light on campus','Unfornately the campus remains dark',
    'Sorry! but there is no electricity on campus','The power hasn\'t still been restored, please check back shortly ',
     'nope.....no power', 'Nothing! yet, please try again shortly']



    if light.state == 'on':
        status = random.choice(success_report)
        pic = 'static/lightbulb.gif'
        color = "#79ff4d"
        report = "The electricity was last restored around"
        t1 = ' #46BC28'
        t2 = '#79ff4d'

    else:
        status = random.choice(failure_report)
        pic = 'static/off.jpeg'
        color = "red"
        report = "The electricity was last interrupted at"
        t1 = 'red'
        t2 = 'red'



    return render_template("electricity/check.html",status = status, pic=pic,color=color,report = report,t1 = t1,t2 = t2, title = title, light = light)




@electricity.route('/off-campus',methods=['GET'])
@login_required  
def offcampus():
    light = Light_sturf_update.query.filter_by(location = 'offcampus').first_or_404()
    pic = 'static/lightbulb.gif'
    color = "#79ff4d"
    status = "status"
    report = "report"
    t1 = "t1"
    t2 = "t2"
    title = "Off campus"


    success_report = ['Cheers! the power has been restored','Hurray! there is power off campus',
        'The power is back!',
        'The power supply has been restored','The electricity is back!','Homes off campus are shining bright! '
        ]

    failure_report = ['oops! no light off campus','Unfornately the streets off campus remain dark',
    'Sorry! but there is no electricity off-campus','The power hasn\'t still been restored, please check back shortly ',
     'electricity is non-existent at the moment', 'Nothing! yet, please try again shortly']


    if light.state == 'on':
        status = random.choice(success_report)
        pic = 'static/lightbulb.gif'
        color = "#79ff4d"
        report = "The electricity was last restored around"
        t1 = ' #46BC28'
        t2 = '#79ff4d'

    else:
        status = random.choice(failure_report)
        pic = 'static/off.jpeg'
        color = "red"
        report = "The electricity was last interrupted at"
        t1 = 'red'
        t2 = 'red'



    return render_template("electricity/check.html",status = status, pic=pic,color=color,report = report,t1 = t1,t2 = t2, title = title, light = light)

app/blueprints/home/views.py
from flask import Blueprint, session, render_template,redirect,url_for,request,flash,redirect,current_app
from flask_security import login_required, current_user,logout_user
from flask_security.forms import LoginForm,RegisterForm
from app.models import User, Notification, Post
from app import db 
from flask_security.utils import hash_password, verify_and_update_password
from app.forms import MoreAboutForm,BirthDayForm,LikesForm,DislikesForm, PostForm, CaptionForm, EventForm, PhoneForm, PhotoForm
from werkzeug.utils import secure_filename
from werkzeug.datastructures import CombinedMultiDict
import secrets
import os
from datetime import datetime
from PIL import Image
import json


from flask import jsonify




index_blueprint = Blueprint('home', __name__, 
    static_folder='static', static_url_path = '/static')



ALLOWED_EXTENSIONS = set(['png', 'jpg', 'jpeg'])



# UPLOAD  PICTURE FUNTIONS

# funtion to check if the uploaded file is in the  allowed file extenion list
def allowed_file(filename):
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS

# funtion that simply returns the file extenion 
def file_ext(filename):
    return str(filename.rsplit('.', 1)[1].lower()) 

# funtion prints the current time of posting in the format -- 'Saturday 17 October 2020'
def current_time():
    return str(datetime.now().strftime("%A %d %B %Y"))











@index_blueprint.route('/view-notifications')
@login_required
def notifications():
    notifications = current_user.new_notifications()

    return render_template("home/notifications.html", notifications = notifications)








@index_blueprint.route('/',methods=['GET']) 
def index():
    return render_template("home/splash.html")


@index_blueprint.route('/general',methods=['GET', 'POST'])  
def general():

    query = request.get_json() or {}

    posts = {}
    post_value = ''

    if current_user.is_authenticated:

        post_value = 'followed'
        posts = current_user.ordered_followed_posts().paginate(per_page = 1000)

    if current_user.is_authenticated and current_user.has_no_followed_posts():
        post_value = 'normal'
        posts = Post.query.join(User).order_by(User.paid.desc()).order_by(Post.date_posted.desc()).paginate( per_page = 10000  )


    try:
        action_type = query['action_type']

        # print('\n', json.dumps(query) )
        
    except KeyError:
        pass

    if request.method == 'POST' and action_type == 'sections' :

        return render_template("home/general-sections.html")


    elif request.method == 'POST' and action_type == 'feed' :

        return render_template("home/general-followed-posts.html", posts = posts, post_value = post_value )


    elif request.method == 'POST' and action_type == 'requests' :

        roomies = current_user.roomie_requesters

        requesters = sorted(roomies, key = lambda x: x.id)

        return render_template("home/general-requests.html", requesters = requesters)




    return render_template("home/general.html", posts = posts, post_value = post_value )





@index_blueprint.route('/vip',methods=['GET'])  
def vip():
    return render_template("home/vip.html")



@index_blueprint.route('/what_more',methods=['GET'])  
def what_more():
    return render_template("home/what_more.html")





@index_blueprint.route('/accept_terms/<email>/<string:answer>',methods=['POST']) 
@login_required 
def terms(email,answer):
    user = User.query.filter_by(email = email).first_or_404()
    user.has_aceepted_terms_and_conditions = bool(answer)
    db.session.commit()
    
    return redirect(url_for('home.general'))






@index_blueprint.route('/feed',methods=['GET'])  
def feed():
    return render_template("home/feed-section.html")





@index_blueprint.route('/sections',methods=['POST'])  
def sections():
    query = request.get_json() or {}

    try:
        action_type = query['action_type']

        print('\n', json.dumps(query) )
        
    except KeyError:
        pass

    # if request.method == 'POST' and post_type == 'Lost Items' :

    return render_template("home/feed-section.html")




@index_blueprint.route('/phone_visibility',methods=['POST']) 
@login_required 
def phone_visibility():

    query = request.get_json() or {}

    # print('\n', json.dumps(query) )

    try:
        user_id = query['user_id']

        phone_visibility = query['phone_visibility']

        # print('\n', json.dumps(query) )

        # print('\n', phone_visibility )
        
    except KeyError:
        pass

    info = 'nothing'

    user = User.query.get_or_404(user_id)


    if phone_visibility and phone_visibility == 'True':
        user.allows_phone_number_to_be_seen = True
        db.session.commit()
        info = ' Your number is now visible to everyone '

    elif phone_visibility and phone_visibility == 'False':
       
        info = ' Only you can see your number from now on'
        user.allows_phone_number_to_be_seen = False
        db.session.commit()

        
    return render_template("home/information.html",info = info )







@index_blueprint.route('/email_visibility',methods=['POST']) 
@login_required 
def email_visibility():

    query = request.get_json() or {}

    # print('\n', json.dumps(query) )

    try:
        user_id = query['user_id']

        email_visibility = query['email_visibility']

        # print('\n', json.dumps(query) )

        # print('\n', email )
        
    except KeyError:
        pass



    info = 'nothing'

    user = User.query.get_or_404(user_id)


    if email_visibility == 'True':
        user.allows_email_to_be_seen = True
        db.session.commit()
        info = ' Your email is now visible to everyone '

    elif email_visibility == 'False':
        print('block entered')
        info = ' Only you can see your email from now on'
        user.allows_email_to_be_seen = False
        db.session.commit()
        
    return render_template("home/information.html",info = info )





#################################
#### USER AND PROFILE ROUTES ####
#################################


@index_blueprint.route('/user/<email>',methods=['GET'])
def user(email):
    user = User.query.filter_by(email = email).first_or_404()
    p = user.image_file
    img = url_for('static', filename = 'profile_pics/uploads/{}'.format(p))
    return render_template("home/user-template.html", user = user, img = img)












@index_blueprint.route('/profile/<id>',methods=['GET','POST'])
@login_required
def profile(id):
    p = current_user.image_file
    img = url_for('static', filename = 'profile_pics/uploads/{}'.format(p))
    user = User.query.get_or_404(id)


    return render_template("home/profile.html", user=user, img = img)
    



@index_blueprint.route('/view-profile-pic/<int:id>',methods=['GET','POST'])
@login_required
def view_profile(id):
    count = request.args.get('count')

    # print(count)

    p = current_user.image_file
    img = url_for('static', filename = 'profile_pics/uploads/{}'.format(p))
    user = User.query.get_or_404(id)


    if user != current_user:
        abort(403)


    photoForm = PhotoForm(CombinedMultiDict((request.files, request.form)))

    # logic for pic upload fields
    if  request.method == 'POST' and photoForm.validate() :
    # logic for uploading profile pic only
    #the request.files object intance using flaskform
        file = photoForm.photo.data
     
        #generate random string 8 digits long
        random_hex = secrets.token_hex(5)


        # check if the post request has the file part
        if not file:
            flash('NO PHOTO CHOSEN', 'error')
            return redirect(request.url)

        # check if the post request has the file part
        elif not  allowed_file(file.filename):
            flash('THE SELECTED FILE TYPE IS NOT ALLOWED, USE png OR jpg FILES ONLY', 'error')
            return redirect(request.url)

     
        # the following if block performs all the required processing on the file
        #and its name after validating its name

        if file and allowed_file(file.filename) and file.filename != '':
            split_file_name = os.path.splitext(file.filename)
            name_list = list(split_file_name)
            ex = str(file_ext(file.filename))
            secure = secure_filename(file.filename)

            #funtion to generate random name
            def random_name(filename):
                random_hex = str(secrets.token_hex(8))
            #the return statement below returns a random name for each file with different parameters separated by underscores 
                return   current_user.first_name + '_' + current_user.last_name + '_' + name_list[0] + '__' + random_hex + '__' + current_time() + '.' + ex


            #the name of the file gets assigned to the randomly generated file name 
            filename  = random_name(file.filename)
          
            uploads_path = os.path.join(current_app.root_path, 'static/profile_pics/uploads', filename)

            #the next four lines just resizes the image to the given dimensions e.g 125 by 125
            output_size = (250,250)
            i = Image.open(file)
            i.thumbnail(output_size)
            i.save(uploads_path)

            #save the newly generated filename to the user database along with other form data
            

            user.image_file = filename
            db.session.commit()


            flash('POST PHOTO UPDATED', 'success')
            return redirect(request.url)

    elif request.method == 'GET':
        photoForm.photo.data = user.image_file




    pic_list = []
    for i in range(2, 11):
        pic_list.append(str(i))




    
    return render_template("home/view-profile.html", user=user, img = img, photoForm = photoForm, pic_list = pic_list, count = count )











@index_blueprint.route('/view-profile-pic/load_more_avatars',methods=['GET','POST'])
@login_required
def load_more_avatars():

app/blueprints/rent/views.py
from flask import Blueprint
from flask import render_template, request
from flask_security import login_required


rent_blueprint = Blueprint('rent', __name__, 
    static_folder='static', static_url_path = '/static')


@rent_blueprint.route('/',methods=['GET'])
@login_required 
def index():
    return render_template("rent/rent.html")

app/templates/home/general-requests.html
<div class = "topicsentence">




		<center class = "pennyless">

				  
		<span style="color: black;"> {{requesters.__len__()}}</span> people sent you a request to be your roomates



				<br>
				<br>	




		




<div class="bio">
	<br>
	<br>


		<div class="bio-content">
			
				{% for user in requesters %}
					<div class="wrapper">

						<a  href="{{url_for('roomie.roomie_requests', request_type = 'requesters' )}}">


							
							<p>


								<img  class="image"  src="{{url_for('static', filename='profile_pics/uploads/' + user.image_file )}}" alt="{{user.first_name}}" width="35" height="35">



								{% if  user.paid %}

								  <i class= "icon" style="text-shadow: none; color: gold; position: absolute; margin-top: -18px; margin-left: -18px;"> &star; </i> 
								
								{% else %}

 								<!-- do nothing -->
								
								{% endif %}

<span style="float: left;"> {{user.first_name}} </span>




								
								 
								 <button class="date" id="request_btn"> Accept </button>

<br>
								



								
							</p>


							


						</a>

					</div>
				{% endfor %}



		</div>
</div>

app/templates/home/general-sections.html
<div id = "advertisement">
		<center> AD</center>
</div>
















<h1 class="penny" >WHERE TO?</h1>






<div class="list-container">

			<a href = '#light1'>
			<div class="list">

			I want to check for electricity

			<main class = "label">

						<div class = "light" /></div>
			</main>

			</div>
		</a>


			<a href = '#light2'>
			<div class="list">

			I want to buy or sell something 

			<main class = "label">

						<div class = "light2" /></div>
			</main>

			</div>
		</a>


		<a href = '#light3'>
			<div class="list">

			I need to buy airtime(VTU),
			<br> 
			pay other bills

			<main class = "label">

						<div class = "light3" /></div>
			</main>

			</div>
		</a>



		<a href = '#light4'>
			<div class="list">

			I want to post something for
			<br>
			the entire campus to see

			<main class = "label">

						<div class = "light4" /></div>
			</main>

			</div>
		</a>





			<a href = '#light6'>
			<div class="list">

			I need a roomate

			<main class = "label">

						<div class = "light6" /></div>
			</main>

			</div>
		</a>



		<a href = '#light5'>
			<div class="list">

			I'm looking for an 
			<br>
			apartment to rent

			<main class = "label">

						<div class = "light5" /></div>
			</main>

			</div>
		</a>



	



</div>












<div class="reduce">




	

	<!-- ..............................section 1............................ -->

	<center>

	<div class="tryme">

		<span></span>
		<span></span>
		<span></span>
		<span></span> 
		








		<main class = "label1">
			<div id = "light1" /></div>
		</main>




		<div id = "textarea">
			<header class="headtext">LIGHT STURF</header>
			<p class="text">Are you on campus wondering if electricity<br> is offcampus?...and vice versa?...</p>




		<center > 
		<div id = "buttonscontainer">

			<div>

				
					<div class = "login">

								{% if current_user.is_anonymous %}


									<a class = "loginbutton" href="{{url_for('security.login')}}">
										<center>LOGIN</center>
									</a>


								{% elif current_user.is_authenticated %}


												
											{% if current_user.login_count >= 10 %}
												
												<a class = "loginbutton" href="{{url_for('electricity.where')}}">
													<center>GO!</center>
												</a>

												{% else %}

												<a class = "loginbutton" href="{{url_for('home.light')}}">
													<center>GO!</center>
												</a>

												{% endif %}


								{% endif %}
						
				
					</div>
				

			</div>
		</div>
		</center>

	</div>

	</center>









	<!-- ..............................section 2............................ -->
	<center>

		<div class="tryme">

				<span></span>
				<span></span>
				<span></span>
				<span></span> 




			<div class = "section">




				<main class = "label1">
					<div id = "light2" /></div>
				</main>




				<div id = "textarea">
					<header class="headtext">COMMERCE STURF</header>
					<p class="text">Buy and Sell items with great ease...</p>

						<center > 

						<div id = "buttonscontainer">

							<center>
								<div class = "login">

									{% if current_user.is_anonymous %}


									<a class = "loginbutton" href="{{url_for('security.login')}}">
										<center>LOGIN</center>
									</a>



									{% elif current_user.is_authenticated %}


												{% if current_user.login_count >= 10 %}

													{% if current_user.is_student  %}
													
													<a class = "loginbutton" href="{{url_for('buy.ads', page = 1, sort = 'normal' )}}">
														<center>GO!</center>
													</a>

													{% else %}


													<a class = "loginbutton" href="{{url_for('buy.buy_user_details' )}}">
														<center>GO!</center>
													</a>



													{% endif %}


												{% else %}

												<a class = "loginbutton" href="{{url_for('home.buy')}}">
													<center>GO!</center>
												</a>

												{% endif %}

									{% endif %}

								</div>
							</center>	

						</div>	
							
				</div>


			</div>


		</div>

	</center>	





	<!-- ..............................section 3............................ -->
	<center>

		<div class="tryme">

				<span></span>
				<span></span>
				<span></span>
				<span></span> 


			<div class = "section">




				<main class = "label1">
					<div id = "light3" /></div>
				</main>




				<div id = "textarea">
					<header class="headtext">RECHARGE & BILLS</header>
					<p class="text">Recharge your phone, Pay other bills,from wherever you are in record time!
					 </p>

						<center > 

							<div id = "buttonscontainer">

								
								<center>
									<div class = "login">


									{% if current_user.is_anonymous %}


									<a class = "loginbutton" href="{{url_for('security.login')}}">
										<center>LOGIN</center>
									</a>


									{% elif current_user.is_authenticated %}


												{% if current_user.login_count >= 10 %}
												
													<a class = "loginbutton" href="{{url_for('home.recharge')}}">
														<center>GO!</center>
													</a>

												{% else %}

													<a class = "loginbutton" href="{{url_for('home.recharge')}}">
														<center>GO!</center>
													</a>

												{% endif %}

									{% endif %}


									</div>

								</center>	

							</div>

						</center>
				</div>





			</div>


		</div>
	</center>




	<!-- ..............................section 4............................ -->
	<center>

			<div class="tryme">

					<span></span>
					<span></span>
					<span></span>
					<span></span> 


				<div class = "section">




					<main class = "label1">
						<div id = "light4" /></div>
					</main>




					<div id = "textarea">
						<header class="headtext">POST STURF</header>
						<p class="text">You are just clicks away from posting anything for 
						hundreds of daily views! both on and off campus</p>

						<center > 

							<div id = "buttonscontainer">
								
								<center>
									<div class = "login">


									{% if current_user.is_anonymous %}


									<a class = "loginbutton" href="{{url_for('security.login')}}">
										<center>LOGIN</center>
									</a>


									{% elif current_user.is_authenticated %}


												{% if current_user.login_count >= 10 %}
												
													<a class = "loginbutton" href="{{url_for('post.post', page = 1, post_type = 'normal')}}">
														<center>GO!</center>
													</a>

												{% else %}

													<a class = "loginbutton" href="{{url_for('home.post_sturf')}}">
														<center>GO!</center>
													</a>

												{% endif %}

									{% endif %}
										

												
									</div>
								</center>

							</div>
						</center>

				</div>


			</div>
	</center>





	<!-- ..............................section 6............................ -->
	<center>

		<div class="tryme">

					<span></span>
					<span></span>
					<span></span>
					<span></span> 


				<div class = "section">

					<main class = "label1">
						<div id = "light6" /></div>
					</main>




					<div id = "textarea">
						<header class="headtext">ROOMIE STURF</header>
						<p class="text">...or maybe you just want to find a compatible roomate ASAP, we got you covered too...</p>

						<center > 

							<div id = "buttonscontainer">

								<center>
									<div class = "login">




									{% if current_user.is_anonymous %}



									<a class = "loginbutton" href="{{url_for('security.login')}}">
										<center>LOGIN</center>
									</a>


									{% elif current_user.is_authenticated %}


												{% if current_user.seeks_roomate %}
												
													<a class = "loginbutton" href="{{url_for('roomie.find_a_roomie', page = 1, sort = 'normal')}}">
														<center>GO!</center>
													</a>

												{% else %}

													<a class = "loginbutton" href="{{url_for('home.roomie')}}">
														<center>GO!</center>
													</a>

												{% endif %}

									{% endif %}




										

												
									</div>
								</center>

							</div>

						</center>


				</div>


		</div>
	</center>



	<!-- ..............................section 5............................ -->
	<center>
		<div class="tryme">

				<span></span>
				<span></span>
				<span></span>
				<span></span> 


			<div class = "section">

				<main class = "label1">
					<div id = "light5" /></div>
				</main>


				<div id = "textarea">
					<header class="headtext">RENT STURF</header>
					<p class="text">Are you having trouble finding a suitable apartment to rent?<br>
					you can start here!...</p>

					<center > 

						<div id = "buttonscontainer">
						
								<center>
									<div class = "login">

										{% if current_user.is_anonymous %}




									<a class = "loginbutton" href="{{url_for('security.login')}}">
										<center>LOGIN</center>
									</a>	


										{% elif current_user.is_authenticated %}

													{% if current_user.login_count >= 10 %}
												
													<a class = "loginbutton" href="{{url_for('rent.index')}}">
														<center>GO!</center>
													</a>

													{% else %}

													<a class = "loginbutton" href="{{url_for('home.rent')}}">
														<center>GO!</center>
													</a>

													{% endif %}


										{% endif %}




									</div>
								</center>		

						</div>
					</center>

				</div>

			</div>
		</div>

	</center>

app/templates/home/information.html
<section style="visibility: visible; font-size: 14px; " class = "information" >


			<p>
				
			{{info}}

			</p>


</section >

app/templates/home/light-sturf.html
<!DOCTYPE html>
<html lang = "en">
<head>
	<title>Sturf Electricity</title>

	<link href="{{url_for('static', filename='light_sturf.css' )}}" rel="stylesheet" type="text/css" />

	<meta name="viewport" content = "width = device-width, initial-scale = 1" charset="utf-8" >


	<script type="text/javascript">

	    function back(){
	    	history.back();
	    }
	    
	</script>

</head> 





<body> 





<!-- header section -->

<div id = "header">

	<label for="check">
		<button  id="btn" type="button" onclick="back()";>&#10094;</button>
	</label>


		
	STURF

	<div class="headtext">
		Improving your wellbeing <span class="dots">...</span>
	</div>


</div>



<!-- end of header section -->







<div class = "topicsentence">
		<center> 
			we all need electricity, wouldn't you like to know
			<span class ="span">where</span> and <span class ="span">when</span>
			it is present?, we are glad to help you with this information
		</center>
</div>




















<div id = "advertisement">
		<center> AD</header>
</div>
















<center>
<div class = "section1">


			<div class="text_container">
				What if i told you there was a site which helps you monitor
				the electricity situation in school and off campus?....and it works like magic

				
			</div>

			<main class = "label1">
				<div class = "light" /></div>
			</main>

			
</div>
</center>
















<center>
<div class = "section2">


			<div class="text_container2">
			Aren't you tired of calling your
			friends to ask about the power situaton on/off campus?
			<!-- <br>
			<a href="#" class="linkr">	Join us, Its Free</a> -->
			</div>

			<main class = "label2">
				<div class = "light2" /></div>
			</main>

			
</div>
</center>








<center>
<div class = "section3">


			<div class="text_container3">
				If you always know where there is 
				electricity then your phone will always be charged,
				therefore you can't fail to prepare for tests and exams. 
			</div>

			<main class = "label3">
				<div class = "light3" /></div>
			</main>

			
</div>
</center>














<center>
<div class = "section4">


<div class="text_container4">
	<!-- PROTECT YOUR GPA FROM THE DANCING COFFIN GUYS!<br>
	<br> -->
	<!-- Don't allow these guys dance with your precious GPA
	be up to date  with electricity easily  -->
	<!-- <br>
	<a href="#" class="linkr">SIGN UP</a> -->
	80% students attribute poor academics to a lack of information about the whereabouts of electricity and as a result their GPA ends up with <span style="font-weight :bolder;">the dancing coffin guys </span>

</div>


<main class = "label4">
	<div class = "light4" /></div>
</main>

			
</div>
</center>





<div id="feedback_container">

<center>
<h1 class="penny" >SHARE WITH PEERS!</h1>
</center>

<center>
<div class="penny-container">

<a href = '#' class="pen">
	<div class = "bgimage1"></div>
</a>

<a href = '#' class="pen">
	<div class = "bgimage2"></div>
</a>

<a href = '#' class="pen">
	<div class = "bgimage3"></div>
</a>

<a href = '#' class="pen">
	<div class = "bgimage4"></div>
</a>

</div>


</center>



</div>






<div id = "buttonscontainer2">



	<div>
		<center>
	<div class = "login">
		
		<a class = "loginbutton" href="{{url_for('electricity.where')}}">
			<center> Proceed &#10095;</center>
		</a>
		</center>		
	</div>
	</div>



</div>









<p class="bottomsentence">This page will disappear after your <span class="linkr2">10th</span> Login</p>









</body>


<!-- ..............................footer............................ -->

<footer id = 'footer'>



<div class="footerians">
	<header><span style="margin-right: 5px; color: #ffffff; font-size: 25px;">☎</span>Get in touch with us</header>

	<ul>

	<li><a href="#"><div class="case1"></div></a></li>
	<li><a href="#"><div class="case2"></div></a></li>
	<li><a href="#"><div class="case3"></div></a></li>
	<li><a href="#"><div class="case4"></div></a></li>

	</ul>
	

</div>



<div class="t_and_t">
	<ul>
	<li><a href="#">Terms and conditions</a></li>
	<li><a href="#">what more can we do?</a></li>
	<li><a href="#">Ad policy</a></li>
	<li><a href="#">Content policy</a></li>
	</ul>
</div>


	

<div id="links">
	<ul>
	<li><a href="#">Home</a></li>
	<li><a href="file:///C:/Users/SIMON/Documents/site%20work/site/Electricity.html">Electricity</a></li>
	<li><a href="#">History</a></li>
	<li><a href="#">About Us</a></li>
	<li><a href="#">FAQS</a></li>
	<li><a href="{{url_for('security.logout')}}">logout</a></li>
	</ul>

</div>


	
<div class="copyright">
	Copyright &copy; 2020-2025 STURF
	All rights reserved.
	STURF is among the federally registered trademarks of
    STURF LLC and may not be used by third parties without explicit permission.


</div>





	
</footer>




</html>

app/templates/home/vip.html
<h1>BENEFITS OF BEING A VIP PAGE!</h1>