app/blueprints/help/views.py
from flask import Blueprint
from flask import render_template, request
from flask_security import login_required


help_blueprint = Blueprint('help', __name__, 
    static_folder='static', static_url_path = '/static')


@help_blueprint.route('/',methods=['GET'])
@login_required   
def index():
    return render_template("help/help.html")

app/blueprints/roomie/views.py
from flask import Blueprint, session, render_template,redirect,url_for,request,flash,redirect,current_app, abort

from flask_security import login_required, current_user,logout_user
from app import db 
from app.models import  Roomie, User, Message, Specific_Message_Read_Time, Comments
from app.forms import RoomieRegisterForm, BasedForm, ReligionForm, LevelForm, MessageForm, BudgetForm
from werkzeug.utils import secure_filename
from werkzeug.datastructures import CombinedMultiDict
import secrets
import os
from datetime import datetime
from PIL import Image
from sqlalchemy import desc



roomie_blueprint = Blueprint('roomie', __name__, 
    static_folder='static', static_url_path = '/static')



@roomie_blueprint.route('/find-a-roomie', methods=['GET'])
@login_required
def find_a_roomie():
    if not current_user.seeks_roomate:
        abort(403)

    page = request.args.get('page', 1, type = int) 
    sort = request.args.get('sort')

    sort_value = 'normal'

    roomies = Roomie.query


    if page != None:

        if sort == 'normal':
            sort_value = 'normal'
            # roomies = Roomie.query.order_by(Roomie.date_joined.desc()).paginate(page = page, per_page = 10  )
            roomies = Roomie.query.join(User).order_by(User.paid.asc()).paginate(page = page, per_page = 10  )

        elif sort == 'Christianity':
            sort_value = 'Christianity'
            roomies =  Roomie.query.filter_by(religion = 'Christianity').join(User).order_by(User.paid.asc()).paginate(page = page, per_page = 10  )

        elif sort == 'Islam':
            sort_value = 'Islam'
            roomies =  Roomie.query.filter_by(religion = 'Islam').join(User).order_by(User.paid.asc()).paginate(page = page, per_page = 10  )

        elif sort == 'religion-other':
            sort_value = 'religion-other'
            roomies =  Roomie.query.filter_by(religion = 'Other').join(User).order_by(User.paid.asc()).paginate(page = page, per_page = 10  )



        elif sort == '100L':
            sort_value = '100L'
            roomies =  Roomie.query.filter_by(level = '100L').join(User).order_by(User.paid.asc()).paginate(page = page, per_page = 10  )


        elif sort == '200L':
            sort_value = '200L'
            roomies =  Roomie.query.filter_by(level = '200L').join(User).order_by(User.paid.asc()).paginate(page = page, per_page = 10  )


        elif sort == '300L':
            sort_value = '300L'
            roomies =  Roomie.query.filter_by(level = '300L').join(User).order_by(User.paid.asc()).paginate(page = page, per_page = 10  )


        elif sort == '400L':
            sort_value = '400L'
            roomies =  Roomie.query.filter_by(level = '400L').join(User).order_by(User.paid.asc()).paginate(page = page, per_page = 10  )



        elif sort == '500L':
            sort_value = '500L'
            roomies =  Roomie.query.filter_by(level = '500L').join(User).order_by(User.paid.asc()).paginate(page = page, per_page = 10  )



        elif sort == 'gidan-kwano':
            sort_value = 'gidan-kwano'
            roomies =  Roomie.query.filter_by(based = 'Gidan Kwano').join(User).order_by(User.paid.asc()).paginate(page = page, per_page = 10  )



        elif sort == 'bosso':       
            sort_value = 'bosso'
            roomies =  Roomie.query.filter_by(based = 'Bosso').join(User).order_by(User.paid.asc()).paginate(page = page, per_page = 10  )



        elif sort == 'based-other':
            sort_value = 'based-other'
            roomies =  Roomie.query.filter_by(based = 'Other').join(User).order_by(User.paid.asc()).paginate(page = page, per_page = 10  )




    return render_template("roomie/find-a-roomie.html", roomies = roomies, sort_value = sort_value)












@roomie_blueprint.route('/roomie-template/<email>', methods=['GET'])
@login_required
def roomie_template(email):
    user = User.query.filter_by(email = email).first_or_404()

    roomie = Roomie.query.filter_by(user_id = user.id).first_or_404()

    budget = roomie.budget
    print (budget)


    p = roomie.candidate.image_file
    img = url_for('static', filename = 'profile_pics/uploads/{}'.format(p))

    return render_template("roomie/roomie-template.html", roomie = roomie, img = img, budget = budget)


























@roomie_blueprint.route('/send-roomie-request/<int:id>/<request_type>', methods=['GET','POST'])
@login_required
def send_roomie_request(id, request_type):
    
    user = User.query.filter_by(id = id).first_or_404()

    if user == current_user:
        abort(403)

    u1 = current_user
    u2 = user

    if request_type == 'request_roomie':
        u1.request_roomie(u2)
        flash('Your request has been sent to {}'.format(user.first_name), 'success')
        u2.add_notification('you_recieved_new_roomie_request', user.roomie_requesters.count())
        db.session.commit()

    elif request_type == 'unrequest_roomie':
        u1.unrequest_roomie(u2)
        flash('Your request to {} has been cancelled'.format(user.first_name), 'success')
        db.session.commit()


    return  redirect(url_for('roomie.find_a_roomie', page = 1, sort = 'normal'))







@roomie_blueprint.route('/remove_roomie/<int:id>/<request_type>', methods=['GET','POST'])
@login_required
def remove_roomie(id,request_type):
    
    user = User.query.filter_by(id = id).first_or_404()

    u1 = current_user
    u2 = user

    if u2 == current_user:
        abort(403)


    if request_type == 'remove':
        if u2.is_following_roomie(u1):
            u2.unfollow_roomie(u1)
            flash(' {} stopped following you because you removed them '.format(user.first_name), 'success')
            db.session.commit()

        elif u1.is_following_roomie(u2):
            u1.unfollow_roomie(u2)
            flash(' you stopped following {}  because you removed them '.format(user.first_name), 'success')
            db.session.commit()



    return  redirect(url_for('roomie.find_a_roomie', page = 1, sort = 'normal'))




@roomie_blueprint.route('/accept-roomie-request/<int:id>', methods=['GET','POST'])
@login_required
def accept_roomie_request(id):
    
    user = User.query.filter_by(id = id).first_or_404()

    requested_user = current_user
    request_sender = user

    if request_sender == current_user:
        abort(403)

    if not request_sender.has_sent_roomie_request_to(requested_user):
        abort(403)

    request_sender.unrequest_roomie(requested_user)

    request_sender.follow_roomie(requested_user)

    request_sender.add_notification('the_other_user_accepted_your_roomie_request', str(requested_user.first_name) )

    db.session.commit()
    flash('you accepted {} \'s request, you can chat them up now'.format(request_sender.first_name), 'success')

    return  redirect(url_for('roomie.find_a_roomie', page = 1, sort = 'normal'))








@roomie_blueprint.route('/roomie-requests/<request_type>', methods=['GET'])
@login_required
def roomie_requests(request_type):

    roomie_type = 'requesters'

    if request_type == 'requesters':
        requesters = current_user.roomie_requesters
        roomie_type = 'requesters'

        # the piece of code below sorts the roomie requesters 
        # by their id since the association table 'roomies' has no date_joined 
        # field but only the two ids of the two users who are roomies 
        # ......this is the only way i found to sort by the latest request
        r = sorted(requesters, key = lambda x: x.id)


    elif request_type == 'roomies':

        requesters = current_user.roomie_followers.union( current_user.is_roomies_with)

        roomie_type = 'roomies'

              

        # the piece of code below sorts the roomie requesters 
        # by their id since the association table 'roomies' has no date_joined 
        # field but only the two ids of the two users who are roomies 
        # ......this is the only way i found to sort by the latest request
        r = sorted(requesters, key = lambda x: x.id)

    return render_template("roomie/roomie-requests.html",requesters = requesters, r=r, request_type = request_type)







@roomie_blueprint.route('/polaroid-person/<email>', methods=['GET'])
@login_required
def polaroid_person(email):
    user = User.query.filter_by(email = email).first_or_404()
    p = user.image_file
    img = url_for('static', filename = 'profile_pics/uploads/{}'.format(p))
    return render_template("roomie/polaroid-person.html", user = user,img = img)







# the route that renders the page to create anouncement post
@roomie_blueprint.route('/roomie-details', methods=['GET', 'POST'])
@login_required
def roomie_details():
    
    form = RoomieRegisterForm()

    if current_user.seeks_roomate:
        abort(403)


    # logic for other post fields
    if  request.method == 'POST' and form.validate() :
    # logic for uploading profile pic only
        #the request.files object intance
        religion = form.religion.data
        level = form.level.data
        based_in =  form.based_in.data
        budget = form.budget.data
     
        
        new_roomie = Roomie(
                religion = religion,
                level = level, 
                based =  based_in,
                budget =  budget,
                date_joined = datetime.utcnow(), 
                candidate = current_user)

        current_user.seeks_roomate = True

        db.session.add(new_roomie)
        db.session.commit()


        flash('Weldone!, henceforth those seeking a roomate will  see you', 'success')
        return redirect(url_for('roomie.find_a_roomie', page = 1, sort = 'normal'))


            
    return render_template('roomie/roomie-details.html',  form = form, page_title = "Hello new roomie, we need the following info to proceed ", val = 'Add Me')







# the route that renders the page to create anouncement post
@roomie_blueprint.route('/roomie-details-update/<id>', methods=['GET', 'POST'])
@login_required
def roomie_details_update(id):
    

app/templates/roomie/find-a-roomie.html
<!DOCTYPE html>
<html lang = "en">
<head>
	<title>Find a roomie with ease</title>

  	<link rel="stylesheet" type="text/css" href="{{url_for('roomie.static', filename='polaroid.css' )}}">

	<meta name="viewport" content = "width = device-width, initial-scale = 1" charset="utf-8" >

	<script src="{{url_for('roomie.static', filename='polaroid.css' )}}"></script>

	<script src="{{url_for('roomie.static', filename='jquery-3.5.1.min.js' )}}"></script>

	<script src="{{url_for('roomie.static', filename='polaroid.js' )}}"></script>

	<meta name="viewport" content = "width = device-width, initial-scale = 1" charset="utf-8" >


	<script type="text/javascript">

    function back(){
    	history.back();
    }
	
	</script>

</head>




<body> 


<!-- header section -->

<div id = "header">

	<label>
        <button  id="back" type="button" onclick="back()";>&#10094;</button>
    </label>


	<a class="header_link" href="{{url_for('home.general')}}">  
    STURF
    </a>












       <!----------- REPORT BUTTON ---------------->
    <input type="checkbox" id="check">

    <label for="check">
        <i  id="btn">═</i>
        <i  id="cancel">╳</i>
    </label>





    <div class="sidebar">

            

    <ul>


        <li >


            <button class="dropdown-btn">
            	<i style="font-style: normal;
               
                 ">

                &#9986;

         		</i>

            	Sort by

            </button>


			  <div class="dropdown-container-a">



			  	<button class="dropdown-btn" style="color:black; font-size:17px;  text-align: right; font-family:  sans-serif;">Conventional</button>
			          <div class="dropdown-container">
			          <a class = "droplink" href="{{url_for('roomie.find_a_roomie', page = 1, sort = 'normal' )}}">Default</a>
			          </div>


			    <button class="dropdown-btn" style="color:black; font-size:17px;  text-align: right; font-family:  sans-serif;">Religion</button>
			          <div class="dropdown-container">
			          <a class = "droplink" href="{{url_for('roomie.find_a_roomie', page = 1, sort = 'Christianity' )}}">Christainity</a>
			          <a class = "droplink" href="{{url_for('roomie.find_a_roomie', page = 1, sort = 'Islam' )}}">Islam</a>
			          <a class = "droplink" href="{{url_for('roomie.find_a_roomie', page = 1, sort = 'religion-other' )}}">Other</a>
			          </div>

			    <button class="dropdown-btn" style="color:black; font-size:17px;  text-align: right; font-family:  sans-serif;">Level</button>
			          <div class="dropdown-container">
			          <a class = "droplink" href="{{url_for('roomie.find_a_roomie', page = 1, sort = '100L' )}}">100l</a>
			          <a class = "droplink" href="{{url_for('roomie.find_a_roomie', page = 1, sort = '200L' )}}">200l</a>
			          <a class = "droplink" href="{{url_for('roomie.find_a_roomie', page = 1, sort = '300L' )}}">300l</a>
			          <a class = "droplink" href="{{url_for('roomie.find_a_roomie', page = 1, sort = '400L' )}}">400l</a>
			          <a class = "droplink" href="{{url_for('roomie.find_a_roomie', page = 1, sort = '500L' )}}">500l</a>
			          </div>

			    <button class="dropdown-btn" style="color:black; font-size:17px;  text-align: right; font-family:  sans-serif;">Current location</button>
			          <div class="dropdown-container">
			          <a class = "droplink" href="{{url_for('roomie.find_a_roomie', page = 1, sort = 'gidan-kwano' )}}">Gidan Kwano</a>
			          <a class = "droplink" href="{{url_for('roomie.find_a_roomie', page = 1, sort = 'bosso' )}}">Bosso</a>
			          <a class = "droplink" href="{{url_for('roomie.find_a_roomie', page = 1, sort = 'based-other' )}}">Other</a>
			          </div>

			  </div>

        </li>





        


    <li>
        <a style="color: gold;" href="{{url_for('post.post_payment_page')}}">

            <i style="font-style: normal;font-size: 30px; margin-right: 0px; color: gold;">&starf;</i>

        VIP

        </a>

    </li>



    <li>
        <a href="{{url_for('help.index')}}">
            <i style="font-style: normal;">&#10067;</i>

        Help 

        </a>

    </li>


    <li>
        <a href="{{url_for('roomie.roomie_details_update', id = current_user.id)}}">
            <i style="font-style: normal;">&#10067;</i>

        Update info

        </a>

    </li>


    <li>
        <a href="{{url_for('roomie.roomie_requests', request_type = 'requesters')}}">
            <i style="font-style: normal;">&#10067;</i>

        Requests

        </a>

    </li>


    <li>
        <a href="{{url_for('roomie.messages')}}">

            <i style="font-style: normal;">&#10067;</i>

            
					{% set new_messages = current_user.new_messages() %}
                    {% if new_messages %}
                    <span class="badge">{{ new_messages }}</span>
                    {% endif %}


        Messages

        </a>

    </li>








    </ul>
            
            

    </div>

<!----------- END OF REPORT BUTTON ---------------->









	<div id="headtext">
		Improving your wellbeing <span class="dots">...</span>
	</div>


</div>



<!-- end of header section -->















{% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}

        <ul class=flashes>

        {% for category, message in messages %}
        	<center>
            <li class="{{ category }}">
                {{ message }}
            </li>
            </center>
        {% endfor %}

        </ul>
        
    {% endif %}
{% endwith %}








{{sort_value}}




{% if roomies.total >= 10 %}



					<div class = "topicsentence">

					       You and
					       {{roomies.total}}
					       others here are searching
					                   
					</div>

			
{% elif roomies.total == 0 %}



		<div class = "topicsentence">
				       
				     Nobody was found
				                   
		</div>

{% elif roomies.total == 1 %}



		<div class = "topicsentence">
				       
				     only one person was found
				                   
		</div>



{% elif roomies.total < 10 %}



		<div class = "topicsentence">
				       
				      {{roomies.total}} people were found
				                   
		</div>



		



{% endif %}





















{% if roomies.total < 10 %}


<a href="#pagination" class="downlink">
		<i>&#10136;</i>
</a>




{% endif %}




























<div class="reduce">
{% for roomie in roomies.items %}


		{% if roomies.total >= 10 %}

											<div class="div">
												<ul class="gallery"> 
											     
													<li draggable="true">

														<img src="{{url_for('static', filename = 'profile_pics/uploads/' +  roomie.candidate.image_file)}}"/>




														{% if roomie.candidate == current_user %}

														<h1>


															you




																{% if roomie.candidate.paid == True  %}

																 <h1> (paid) </h1>

																{% endif %}

														</h1>

														{% else %}

														<h1>

															{{roomie.candidate.first_name.lower()}}  rid:{{roomie.id}} uid:{{roomie.candidate.id}} rela:{{roomie.candidate}}


																{% if roomie.candidate.paid == True  %}

																 <h1> (paid) </h1>

																{% endif %}



														</h1>

														{% endif %}




													


														<a href="{{url_for('roomie.roomie_template', email = roomie.candidate.email )}}" target="_blank">
														<p>view bio</p>
														</a>
													</li> 

												</ul> 
											</div>

		{% elif roomies.total < 10 %}





										<div class="cover">


											
											
												
												<main class = "label1">
														<div  class="image" style="background: url('{{url_for('static', filename = 'profile_pics/uploads/' +  roomie.candidate.image_file)}}') no-repeat center;
																				background-size: cover;
																				"

													 					/>
													 						

													 	</div>
												</main>

												{% if roomie.candidate == current_user %}

												<h1>you</h1>

												{% else %}

												<h1>{{roomie.candidate.first_name.lower()}} </h1>

												{% endif %}



												{% if roomie.candidate.paid == True  %}

																 <h1> (paid) </h1>

																{% endif %}
											


												<a href="{{url_for('roomie.roomie_template', email = roomie.candidate.email )}}" target="_blank">
												<p>view bio</p>
												</a>

											


										</div>

		{% endif %}


{%endfor%}

</div>
</body> 









<!-- javascript handling the dropdown menu -->
<script>
/* Loop through all dropdown buttons to toggle between hiding and showing its dropdown content - This allows the user to have multiple dropdowns without any conflict */
var dropdown = document.getElementsByClassName("dropdown-btn");
var i;

for (i = 0; i < dropdown.length; i++) {
  dropdown[i].addEventListener("click", function() {
    this.classList.toggle("active");
    var dropdownContent = this.nextElementSibling;
    if (dropdownContent.style.display === "block") {
      dropdownContent.style.display = "none";
    } else {
      dropdownContent.style.display = "block";
    }
  });
}
</script>
































		<center>
		    <div id="pagination"> 
		    {% for page_num in roomies.iter_pages(left_edge=1, right_edge = 1, left_current = 1, right_current = 2) %}


		        {%if page_num %}

		            {%if roomies.page == page_num%}
		            <a  class="pagination_highlight" href="{{url_for('roomie.find_a_roomie', page = page_num, sort = sort_value )}}">{{page_num}}</a>

		            {% else %}

		             <a  class="pagination_normal" href="{{url_for('roomie.find_a_roomie', page = page_num, sort = sort_value )}}">{{page_num}}</a>
		            {% endif %}

		        {% else %}

		        ...


		        {% endif %}



		    {% endfor %}
		    </div>
		</center>



<!-- ..............................footer............................ -->

<footer id = 'footer'>



<div class="footerians">
	<header><span style="margin-right: 5px; color: #ffffff; font-size: 25px;">☎</span>Get in touch with us</header>

	<ul>

	<li><a href="#"><div class="case1"></div></a></li>
	<li><a href="#"><div class="case2"></div></a></li>
	<li><a href="#"><div class="case3"></div></a></li>
	<li><a href="#"><div class="case4"></div></a></li>

	</ul>
	

</div>



<div class="t_and_t">
	<ul>
	<li><a href="#">Terms and conditions</a></li>
	<li><a href="#">what more can we do?</a></li>
	<li><a href="#">Ad policy</a></li>
	<li><a href="#">Content policy</a></li>
	</ul>
</div>


	

<div id="links">
	<ul>
	<li><a href="#">Home</a></li>
	<li><a href="file:///C:/Users/SIMON/Documents/site%20work/site/Electricity.html">Electricity</a></li>
	<li><a href="#">History</a></li>
	<li><a href="#">About Us</a></li>
	<li><a href="#">FAQS</a></li>
	<li><a href="{{url_for('security.logout')}}">logout</a></li>
	</ul>

</div>


	
<div class="copyright">
	Copyright &copy; 2020-2025 STURF
	All rights reserved.
	STURF is among the federally registered trademarks of
    STURF LLC and may not be used by third parties without explicit permission.


</div>





	
</footer>



</html>

app/templates/roomie/roomie-template.html
<!DOCTYPE html>
<html lang = "en">
<head>
	<title>{{roomie.candidate.first_name}}</title>

	<link href="{{url_for('roomie.static', filename='roomie-template.css' )}}" rel="stylesheet" type="text/css" />

	<meta name="viewport" content = "width = device-width, initial-scale = 1" charset="utf-8" >

	<script type="text/javascript">

    function die(){
    	window.close();
    }
	
	</script>



</head> 





<body> 



<div id = "header">

<label for="check">
		<buttom  id="btn" type="button" onclick="die()";>&#10006;</button>
</label>


		<a class="header_link" href="{{url_for('home.general')}}">	
		STURF
		</a>


<div class="headtext">
	Improving your wellbeing <span class="dots">...</span>
</div>


</div>

























<center>

<div class="tryme">

	<span></span>
	<span></span>
	<span></span>
	<span></span> 
	
		<div class = "section1">


					<div class="text_container">
						<p class="p1">


								{% if  current_user == roomie.candidate%}

								You

								{% else%}

								{{roomie.candidate.first_name.upper()}}

								{% endif %}
						
						</p>
						<p class="p2">
							<span style="background-color: white;  border-radius: 25px 25px 0px 25px;" class="tooltiptext">
							        
									{% if  current_user ==  roomie.candidate%}

									Your Caption

									{% else%}

									{{roomie.candidate.first_name.upper()}}'s Caption

									{% endif %}
																

							</span>

							{% if  current_user ==  roomie.candidate%}

							You are

							{% else%}

							<b>{{roomie.candidate.first_name}}</b> is

							{% endif %}




							{{roomie.candidate.caption}}
							
						</p>


						<p class="p2">

							{% if  current_user.is_authenticated  %}

								<p class="online_indicator">
								<b> last login:</b> 
								{{roomie.candidate.last_login_at.strftime("%I : %M  %p ")}}
								</p>
	
							{% endif %}
						
						</p>



					</div>



					<main class = "label1">

						<a href="{{url_for('roomie.polaroid_person', email = roomie.candidate.email )}}">
					    
					    
						<div id="light" 
						style="background: url('{{img}}') no-repeat center;
								background-size: cover;
								width: 100%;
								height:100%;
								padding-top: 100%;
								border-radius: 15px 150px 150px 150px;
								margin-left: 15px;
								margin-top: 3px;
								vertical-align: center;
								max-width: 200px;
								max-height: 200px;
								border: 0.5px solid #79ff4d"

	 					/></div>

	 					</a>
					</main>

					
		</div>
</div>
</center>





<div class="contact">
	<h1>CONTACT</h1>
	<br>
	<br>
		<div class="contact-content">

			{% if roomie.candidate.phone %}

			<p><span> <i style="color: black; font-style: normal;">&phone;</i>Tel: </span>{{roomie.candidate.phone}}

			</p>
			{% endif %}



			<br>

			{% if roomie.candidate.email %}

			<p><span><i style="color: black; font-style: normal; font-size:23px;">&commat;</i>Email: </span> 


						{{roomie.candidate.email}}


						</p>


			{% endif %}

		</div>
	
</div>


<div class="bio">
	<h1>BIO</h1>
	<br>
	<br>
		<div class="bio-content">
			<center>

				{% if roomie.candidate.more_about %}
				<p>
					<span>

						<i style="color: black; font-style: normal;font-size:30px;">&#9997;</i>More about {{roomie.candidate.first_name}}</span><br>
						{{roomie.candidate.more_about}}
				</p>

				{% endif %}

				<br>


				{% if roomie.candidate.birth_day %}
				<p><span>

					<i style="color: black; font-style: normal;font-size:30px;">&#9832;</i>Birthday </span> <br>
					{{roomie.candidate.birth_day}}
				</p>

				{% endif %}


				{% if roomie.candidate.likes %}
				<p><span>

					<i style="color: black; font-style: normal; font-size:30px;">&#10084;</i>{{roomie.candidate.first_name}} likes </span> <br>
					{{roomie.candidate.likes}}
				</p>

				{% endif %}


				{% if roomie.candidate.dislikes %}
				<p>
					<span>

					<i style="color: black; font-style: normal; font-size:30px; ">&#9876;</i>{{roomie.candidate.first_name}} dislikes 
					</span> 

					<br>
					{{roomie.candidate.dislikes}}
				</p>

				{% endif %}





				<p>
					<span>

					<i style="color: black; font-style: normal;  font-size:30px;">&#9876;</i>Level
					</span> 

					<br>
					{{roomie.level}}
				</p>



				<p>
					<span>

					<i style="color: black; font-style: normal;  font-size:30px;">&#9876;</i>Based currently in
					</span> 

					<br>
					{{roomie.based}}
				</p>




				<p>
					<span>


					{% if roomie.religion == "Christianity" %}
					<i style="color: black; font-style: normal; font-size:30px; ">

						&#10015;

					</i>
					{% elif roomie.religion == "Islam" %}

					<i style="color: black; font-style: normal; font-size:30px; ">

						&#9770;

					</i>

					{% elif roomie.religion == "other" %}

					<i style="color: black; font-style: normal; font-size:30px;">

						&#10022;

					</i>

					{% endif %}





					Religion 
					</span> 

					<br>
					{{roomie.religion}}
				</p>







				<p>
					<span>

					<i style="color: black; font-style: normal;  font-size:30px;">&#9876;</i>

					{{roomie.candidate.first_name}} can afford an amount

					</span> 

					<br>
					{{ roomie.budget }}
				</p>








				<p>
					<span>

					<i style="color: black; font-style: normal;  font-size:30px;">&#9876;</i>

					started searching on

					</span> 

					<br>
					{{roomie.date_joined.strftime("%A, %d %B %Y")}}
				</p>





				

			</center>
		</div>
</div>








<center>

<!-- if the curremt_user has sent the other user -->
{% if current_user.has_sent_roomie_request_to(roomie.candidate) %}



				{% if roomie.candidate != current_user %}


				<center>you have sent <b>{{ roomie.candidate.first_name }} </b>a roomie request</center>
				<br>
				<br>
				<br>

							<a  href="{{url_for('roomie.send_roomie_request', id = roomie.candidate.id, request_type = 'unrequest_roomie') }}" >
				             Cancel Request
				            </a>
				{% endif %}





{% elif  roomie.candidate.has_sent_roomie_request_to(current_user) %}

				
				{% if roomie.candidate != current_user %}


					<b>{{ roomie.candidate.first_name }}</b> already sent you a roomie request, check your  <a href="{{url_for('roomie.roomie_requests', request_type = 'requesters' )}}"> Requests </a>

				{% endif %}







{% elif  roomie.candidate.is_following_roomie(current_user) %}

				
				{% if roomie.candidate != current_user %}

							<center>you accepted <b>{{ roomie.candidate.first_name }}'s</b> roomie request, now they are following you</center>

				{% endif %}






{% elif  current_user.is_following_roomie(roomie.candidate) %}

				
				{% if roomie.candidate != current_user %}

							<center> <b>{{ roomie.candidate.first_name }}</b> accepted your roomie request, now you are following them </center>

				{% endif %}







{% else %} 

				{% if roomie.candidate != current_user %}


				            <a  href="{{url_for('roomie.send_roomie_request', id = roomie.candidate.id, request_type = 'request_roomie') }}" >
				             Send Request
				            </a>
				{% endif %}



{% endif %} 
				

		

<br>
<br>
<br>
<br>
<br>

				            <a  href="{{url_for('roomie.remove_roomie', id = roomie.candidate.id, request_type = 'remove') }}" >
				             remove roomie
				            </a>




</center>



























</body>



<footer id = 'footer'>



<div class="footerians">
	<header><span style="margin-right: 5px; color: #ffffff; font-size: 25px;">☎</span>Get in touch with us</header>

	<ul>

	<li><a href="#"><div class="case1"></div></a></li>
	<li><a href="#"><div class="case2"></div></a></li>
	<li><a href="#"><div class="case3"></div></a></li>
	<li><a href="#"><div class="case4"></div></a></li>

	</ul>
	

</div>



<div class="t_and_t">
	<ul>
	<li><a href="#">Terms and conditions</a></li>
	<li><a href="#">what more can we do?</a></li>
	<li><a href="#">Ad policy</a></li>
	<li><a href="#">Content policy</a></li>
	</ul>
</div>


	

<div class="links">
	<ul>
	<li><a href="#">Home</a></li>
	<li><a href="file:///C:/Users/SIMON/Documents/site%20work/site/Electricity.html">Electricity</a></li>
	<li><a href="#">History</a></li>
	<li><a href="#">About Us</a></li>
	<li><a href="#">FAQS</a></li>
	<li><a href="{{url_for('security.logout')}}">logout</a></li>
	</ul>

</div>


	
<div class="copyright">
	Copyright &copy; 2020-2025 STURF
	All rights reserved.
	STURF is among the federally registered trademarks of
    STURF LLC and may not be used by third parties without explicit permission.


</div>





	
</footer>





</html>