app/blueprints/electricity/views.py
from flask import Blueprint, render_template, request
from flask_security import login_required
import sqlite3
from datetime import datetime
import time
import random
from app.models import Light_sturf, Light_sturf_update
from app import db 


electricity = Blueprint('electricity', __name__, 
    static_folder='static', static_url_path = '/static')



@electricity.route('/')
@login_required 
def where():
    return render_template("electricity/where.html")


#this route saves all date gotten as query parameters
@electricity.route('/BtfT2GB2h9s4kP_cjZdqkSv5Bps/api-save',methods=['GET'])
def api_save():
    #this function populates the light_sturf table
    def Light_list():
        location = request.args.get('location',  type = str)
        state = request.args.get('state',  type = str) 


        first = Light_sturf(
                        location = location,
                        state = state
                        )


        db.session.add(first)
        db.session.commit()


    #this function updates the light_sturf table which has only a single row
    def Light_update():
        
        location = request.args.get('location',  type = str)
        state = request.args.get('state',  type = str) 

        Light_update = Light_sturf_update.query.filter_by(location = location).first_or_404()

        Light_update.location = location
        Light_update.state = state


       
        db.session.commit()


 
    Light_list()
    Light_update()

    return render_template("electricity/testing.html", location = request.args.get('location',  type = str), state = request.args.get('state',  type = str))
    


# @electricity.route('/first/api-save',methods=['GET'])
# def api_save():
#     location = request.args.get('location',  type = str)
#     status = request.args.get('status',  type = str) 


#     Light_sturf.location = location
#     Light_sturf.status = status


#     light_sturf = Light_sturf(
#                     image_file = filename,
#                     title = title, 
#                     content =  content, 
#                     author = current_user)

 

#     return render_template("electricity/testing.html", location = location, status = status)



@electricity.route('/campus',methods=['GET'])
@login_required  
def campus():
    light = Light_sturf_update.query.filter_by(location = 'campus').first_or_404()
    pic = 'static/lightbulb.gif'
    color = "#79ff4d"
    status = "status"
    report = "report"
    t1 = "t1"
    t2 = "t2"
    title = "Campus"

    success_report = ['Cheers! the power has been restored','Hurray! there is power off campus',
        'The power is back!',
        'The power supply has been restored','The electricity is back!','Homes off campus are shining bright! '
        ]

    failure_report = ['oops! no light on campus','Unfornately the campus remains dark',
    'Sorry! but there is no electricity on campus','The power hasn\'t still been restored, please check back shortly ',
     'nope.....no power', 'Nothing! yet, please try again shortly']



    if light.state == 'on':
        status = random.choice(success_report)
        pic = 'static/lightbulb.gif'
        color = "#79ff4d"
        report = "The electricity was last restored around"
        t1 = ' #46BC28'
        t2 = '#79ff4d'

    else:
        status = random.choice(failure_report)
        pic = 'static/off.jpeg'
        color = "red"
        report = "The electricity was last interrupted at"
        t1 = 'red'
        t2 = 'red'



    return render_template("electricity/check.html",status = status, pic=pic,color=color,report = report,t1 = t1,t2 = t2, title = title, light = light)




@electricity.route('/off-campus',methods=['GET'])
@login_required  
def offcampus():
    light = Light_sturf_update.query.filter_by(location = 'offcampus').first_or_404()
    pic = 'static/lightbulb.gif'
    color = "#79ff4d"
    status = "status"
    report = "report"
    t1 = "t1"
    t2 = "t2"
    title = "Off campus"


    success_report = ['Cheers! the power has been restored','Hurray! there is power off campus',
        'The power is back!',
        'The power supply has been restored','The electricity is back!','Homes off campus are shining bright! '
        ]

    failure_report = ['oops! no light off campus','Unfornately the streets off campus remain dark',
    'Sorry! but there is no electricity off-campus','The power hasn\'t still been restored, please check back shortly ',
     'electricity is non-existent at the moment', 'Nothing! yet, please try again shortly']


    if light.state == 'on':
        status = random.choice(success_report)
        pic = 'static/lightbulb.gif'
        color = "#79ff4d"
        report = "The electricity was last restored around"
        t1 = ' #46BC28'
        t2 = '#79ff4d'

    else:
        status = random.choice(failure_report)
        pic = 'static/off.jpeg'
        color = "red"
        report = "The electricity was last interrupted at"
        t1 = 'red'
        t2 = 'red'



    return render_template("electricity/check.html",status = status, pic=pic,color=color,report = report,t1 = t1,t2 = t2, title = title, light = light)

app/blueprints/history/views.py
from flask import Blueprint
from flask import render_template, request
from flask_security import login_required
from app.models import Light_sturf
import sqlite3


history_blueprint = Blueprint('history', __name__, 
    static_folder='static', static_url_path = '/static')


@history_blueprint.route('/',methods=['GET'])
@login_required 
def history():
    rows = Light_sturf.query.order_by(Light_sturf.period.desc()).limit(10)
    
    return render_template("history/history.html", rows = rows)





@history_blueprint.route('/paginated_history',methods=['GET'])
@login_required 
def history_paginated():

	page = request.args.get('page', 1, type = int)
	rows = Light_sturf.query.order_by(Light_sturf.period.desc()).paginate(page = page, per_page = 10 )

	return render_template("history/history_paginated.html", rows = rows)

app/templates/electricity/check.html
<!DOCTYPE html>
<html lang = "en">
<head>
	<script>
		 // Function to change div background color
    
    function reloader(){
    	window.location.reload(true);
    }

    function back(){
        history.back();
        history.back();
    }


	</script>

	<title>{{title}}</title>

	<link href="{{url_for('electricity.static', filename='location.css' )}}" rel="stylesheet" type="text/css" />

	<meta name="viewport" content = "width = device-width, initial-scale = 1" >

</head> 




<body> 




<!-- header section -->

<div id = "header">

	<label for="check">
		<button  id="btn" type="button" onclick="back()";>&#10094;</button>
	</label>


		
	STURF

	<div class="headtext">
		Improving your wellbeing <span class="dots">...</span>
	</div>


</div>



<!-- end of header section -->








<div id = "advertisement">
		<center> AD</header>
</div>









<div id = "textarea">


	<center class="text" > 

		Keep refreshing this page regularly to see the update on electricity.
		<br>
		We have provided a convenient refresh button below

	</center>

	



	<hr style="max-width: 500px; margin: 0 auto;">





	<h1 style= "
	  font-size: 37px;
	  margin-bottom: 120px;
	  margin-top: 120px;
	  text-transform: uppercase;
	  line-height: 45px;
	  letter-spacing: 3px;
	  font-weight: 200;
	  text-align: center;
	  font-family:cursive, sans-serif;
	  text-shadow: 2px 0px 3px rgba(28,110,164,0.48);
	  transition: all ease 9s;
	  color: {{t2}};"
	>

	{{status}}

	</h1>





	<hr style="max-width: 500px; margin: 0 auto; ">





	<h3  style="	
	max-width: 500px;
	text-align: center;
	margin: 0 auto;
	margin-top: 150px;
	margin-bottom: 150px;
	font-size: 22px;
	font-family: 'Lucida Sans Unicode', 'Lucida Grande', sans-serif;"> 

				{{report}} 

				<span style = "
				color: {{t1}}; 
				font-family:cursive, sans-serif; 
				font-size: 30px;"> 
				<br>

				{{light.period.strftime("%I:%M%p  %A, %B %d")}}


				</span>


	</h3>


	
</div>











<div >

	<center> 

		<main style="	min-height:200px;
			background-color: {{color}};
			position: relative;
			border-radius: 15px;
			text-align: center;
			margin-bottom: 60px;
			margin-top: 60px;
			box-shadow: 5px 4px 17px 3px #848484;
			max-width: 500px;
			margin-top: 5%;
			max-height: 500px;
		">




						<div id="bgimage" style = "
							vertical-align: center;
							background: url('{{pic}}') no-repeat center;
							background-size: contain;
							width: 100%;
							height:100%;
							padding-top: 100%;
							border-radius: 50%;
						}">
							

						</div>
		
		</main>

	</center>

</div>





<div id = "linkcontainer">

	<div>
		<center>
	<div class = "login">
		
		<button style = 'margin-top:70px; outline: none;' class = "loginbutton" type="button" onclick="reloader();">
			<center>Refresh</center>
		</button>
		</center>		
	</div>
	</div>

</div>



<center > 
<div id = "linkcontainer">

	<div>
		<center>
	<div class = "login">
		
		<a class = "loginbutton" href="{{url_for('history.history')}}">
			<center>History</center>
		</a>
		</center>		
	</div>
	</div>
</div>
</div>
</center>



</body>









<!-- ..............................footer............................ -->

<footer id = 'footer'>



<div class="footerians">
	<header><span style="margin-right: 5px; color: #ffffff; font-size: 25px;">☎</span>Get in touch with us</header>

	<ul>

	<li><a href="#"><div class="case1"></div></a></li>
	<li><a href="#"><div class="case2"></div></a></li>
	<li><a href="#"><div class="case3"></div></a></li>
	<li><a href="#"><div class="case4"></div></a></li>

	</ul>
	

</div>



<div class="t_and_t">
	<ul>
	<li><a href="#">Terms and conditions</a></li>
	<li><a href="#">what more can we do?</a></li>
	<li><a href="#">Ad policy</a></li>
	<li><a href="#">Content policy</a></li>
	</ul>
</div>


	

<div id="links">
	<ul>
	<li><a href="#">Home</a></li>
	<li><a href="file:///C:/Users/SIMON/Documents/site%20work/site/Electricity.html">Electricity</a></li>
	<li><a href="#">History</a></li>
	<li><a href="#">About Us</a></li>
	<li><a href="#">FAQS</a></li>
	<li><a href="{{url_for('security.logout')}}">logout</a></li>
	</ul>

</div>


	
<div class="copyright">
	Copyright &copy; 2020-2025 STURF
	All rights reserved.
	STURF is among the federally registered trademarks of
    STURF LLC and may not be used by third parties without explicit permission.


</div>





	
</footer>





<html>

app/templates/electricity/location.html
<!DOCTYPE html>
<html lang = "en">
<head>
	<script>
		 // Function to change div background color
    
    function reloader(){
    	window.location.reload(true);
    }

    function back(){
        history.back();
        history.back();
    }


	</script>

	<title>{{title}}</title>

	<link href="{{url_for('electricity.static', filename='location.css' )}}" rel="stylesheet" type="text/css" />

	<meta name="viewport" content = "width = device-width, initial-scale = 1" >

</head> 




<body> 




<!-- header section -->

<div id = "header">

	<label for="check">
		<button  id="btn" type="button" onclick="back()";>&#10094;</button>
	</label>


		
	STURF

	<div class="headtext">
		Improving your wellbeing <span class="dots">...</span>
	</div>


</div>



<!-- end of header section -->








<div id = "advertisement">
		<center> AD</header>
</div>









<div id = "textarea">


	<center class="text" > 

		Keep refreshing this page regularly to see the update on electricity.
		<br>
		We have provided a convenient refresh button below

	</center>

	



	<hr style="max-width: 500px; margin: 0 auto;">





	<h1 style= "
	  font-size: 37px;
	  margin-bottom: 120px;
	  margin-top: 120px;
	  text-transform: uppercase;
	  line-height: 45px;
	  letter-spacing: 3px;
	  font-weight: 200;
	  text-align: center;
	  font-family:cursive, sans-serif;
	  text-shadow: 2px 0px 3px rgba(28,110,164,0.48);
	  transition: all ease 9s;
	  color: {{t2}};"
	>

	{{status}}

	</h1>





	<hr style="max-width: 500px; margin: 0 auto; ">





	<h3  style="	
	max-width: 500px;
	text-align: center;
	margin: 0 auto;
	margin-top: 150px;
	margin-bottom: 150px;
	font-size: 22px;
	font-family: 'Lucida Sans Unicode', 'Lucida Grande', sans-serif;"> 

				{{report}} 

				<span style = "
				color: {{t1}}; 
				font-family:cursive, sans-serif; 
				font-size: 30px;"> 

				{{era}}


				</span>


	</h3>


	
</div>











<div >

	<center> 

		<main style="	min-height:200px;
			background-color: {{color}};
			position: relative;
			border-radius: 15px;
			text-align: center;
			margin-bottom: 60px;
			margin-top: 60px;
			box-shadow: 5px 4px 17px 3px #848484;
			max-width: 500px;
			margin-top: 5%;
			max-height: 500px;
		">




						<div id="bgimage" style = "
							vertical-align: center;
							background: url('{{pic}}') no-repeat center;
							background-size: contain;
							width: 100%;
							height:100%;
							padding-top: 100%;
							border-radius: 50%;
						}">
							

						</div>
		
		</main>

	</center>

</div>





<div id = "linkcontainer">

	<div>
		<center>
	<div class = "login">
		
		<button style = 'margin-top:70px; outline: none;' class = "loginbutton" type="button" onclick="reloader();">
			<center>Refresh</center>
		</button>
		</center>		
	</div>
	</div>

</div>



<center > 
<div id = "linkcontainer">

	<div>
		<center>
	<div class = "login">
		
		<a class = "loginbutton" href="http://192.168.43.27:70/history">
			<center>History</center>
		</a>
		</center>		
	</div>
	</div>
</div>
</div>
</center>



</body>









<!-- ..............................footer............................ -->

<footer id = 'footer'>



<div class="footerians">
	<header><span style="margin-right: 5px; color: #ffffff; font-size: 25px;">☎</span>Get in touch with us</header>

	<ul>

	<li><a href="#"><div class="case1"></div></a></li>
	<li><a href="#"><div class="case2"></div></a></li>
	<li><a href="#"><div class="case3"></div></a></li>
	<li><a href="#"><div class="case4"></div></a></li>

	</ul>
	

</div>



<div class="t_and_t">
	<ul>
	<li><a href="#">Terms and conditions</a></li>
	<li><a href="#">what more can we do?</a></li>
	<li><a href="#">Ad policy</a></li>
	<li><a href="#">Content policy</a></li>
	</ul>
</div>


	

<div id="links">
	<ul>
	<li><a href="#">Home</a></li>
	<li><a href="file:///C:/Users/SIMON/Documents/site%20work/site/Electricity.html">Electricity</a></li>
	<li><a href="#">History</a></li>
	<li><a href="#">About Us</a></li>
	<li><a href="#">FAQS</a></li>
	<li><a href="{{url_for('security.logout')}}">logout</a></li>
	</ul>

</div>


	
<div class="copyright">
	Copyright &copy; 2020-2025 STURF
	All rights reserved.
	STURF is among the federally registered trademarks of
    STURF LLC and may not be used by third parties without explicit permission.


</div>





	
</footer>





<html>

app/templates/electricity/testing.html
<!Doctype html>
<html>
   <body>

   	<!-- type of location is --- {{var1}}
   	type of status is --- {{var2}} -->
<!--    	<br>
      result  : {{ msg }}

      <br>
      <br>
      <br>
      <br>

      result of recording : {{ record_msg }}

      <br>
      <br>
      <br>
      <br>

      supposed error: {{error}} -->




<br>
      <br>
      <br>
      <br>
      <br>
<h1>current paramters:</h1>
<br>
      <br>
    
this location is ------------->{{ location }}
      <br>
   




the status is --------------->{{ state }}

<br>
      <br>
      <br>
      <br>   

      save sucesssful


      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>

{%if population %}
      <div>
      	<ul>
      		{% for item in population%}
      		<li>{{item}}</li>
      		{%endfor%}
      	</ul>
      </div>
{%endif%}
     
     

     <!-- <h1>{{loc}}</h1>
     <h1>{{stat}}</h1> -->
      		
   </body>
</html>

app/templates/electricity/where.html
<!DOCTYPE html>
<html lang = "en">

<head>
	<title>Where do you want to check?</title>

	<link href="{{url_for('electricity.static', filename='where.css' )}}" rel="stylesheet" type="text/css" />

	<meta name="viewport" content = "width = device-width, initial-scale = 1" charset="utf-8" >

	<script type="text/javascript">
    function back(){
        history.back();
       
    }
	</script>

</head>





<body> 




<!-- header section -->

<div id = "header">

	<label for="check">
		<button  id="btn" type="button" onclick="back()";>&#10094;</button>
	</label>


		
	STURF

	<div id="headtext">
		Improving your wellbeing <span class="dots">...</span>
	</div>


</div>



<!-- end of header section -->












<div id = "advertisement">
		<center> AD</center>
</div>











<div class="reduce">

			<h1 class="penny" >WHERE DO YOU WANT TO CHECK?</h1>


			<!-- ..............................section ............................ -->

			<center>
			<div class="tryme">

				<span></span>
				<span></span>
				<span></span>
				<span></span> 
				

			<main class = "label1">
				<div class = "light" /></div>
			</main>




			<div id = "textarea">
				<header class="headr">CAMPUS</header>
				

			<center > 

			<div id = "buttonscontainer">



				<div>
					<center>
				<div class = "login">
					
					<a class = "loginbutton" href="{{url_for('electricity.campus')}}">
						<center>CHECK</center>
					</a>
					</center>		
				</div>
				</div>



			</div>


			</div>
			</center>


			 <!-- ----------------------------------------------------------------------------------------
 -->



			<!-- ..............................section ............................ -->

			<center>
			<div class="tryme">

				<span></span>
				<span></span>
				<span></span>
				<span></span> 
				


			<main class = "label1">
				<div class = "light2" /></div>
			</main>


			<div id = "textarea">
				<header class="headr">OFF CAMPUS</header>
				

			<center > 

			<div id = "buttonscontainer">



				<div>
					<center>
				<div class = "login">
					
					<a class = "loginbutton" href="{{url_for('electricity.offcampus')}}">
						<center>CHECK</center>
					</a>
					</center>		
				</div>
				</div>





			</div>

				

			</div>
			</center>

			<!-- ------------------------------------------------------------------------------------------>

</div>


</body>











<!-- ..............................footer............................ -->

<footer id = 'footer'>



<div class="footerians">
	<header><span style="margin-right: 5px; color: #ffffff; font-size: 25px;">☎</span>Get in touch with us</header>

	<ul>

	<li><a href="#"><div class="case1"></div></a></li>
	<li><a href="#"><div class="case2"></div></a></li>
	<li><a href="#"><div class="case3"></div></a></li>
	<li><a href="#"><div class="case4"></div></a></li>

	</ul>
	

</div>



<div class="t_and_t">
	<ul>
	<li><a href="#">Terms and conditions</a></li>
	<li><a href="#">what more can we do?</a></li>
	<li><a href="#">Ad policy</a></li>
	<li><a href="#">Content policy</a></li>
	</ul>
</div>


	

<div id="links">
	<ul>
	<li><a href="#">Home</a></li>
	<li><a href="file:///C:/Users/SIMON/Documents/site%20work/site/Electricity.html">Electricity</a></li>
	<li><a href="#">History</a></li>
	<li><a href="#">About Us</a></li>
	<li><a href="#">FAQS</a></li>
	<li><a href="{{url_for('security.logout')}}">logout</a></li>
	</ul>

</div>


	
<div class="copyright">
	Copyright &copy; 2020-2025 STURF
	All rights reserved.
	STURF is among the federally registered trademarks of
    STURF LLC and may not be used by third parties without explicit permission.


</div>





	
</footer>



</html>