app/blueprints/buy/views.py
from flask import Blueprint, session, render_template,redirect,url_for,request,flash,current_app, abort

from flask_security import login_required, current_user,logout_user
from app import db 
from app.models import  User, E_commerce

from app.forms import  EventForm , TitleForm, ContentForm, VenueForm, BirthDayForm, \
LinkForm, PhoneForm, CommentForm, StudentForm, AdForm, TabletAdForm, MultiPhotoForm, WhatssapForm, AddressForm
from werkzeug.utils import secure_filename
from werkzeug.datastructures import CombinedMultiDict
import secrets
import os
from datetime import datetime
from PIL import Image


buy_blueprint = Blueprint('buy', __name__, 
    static_folder='static', static_url_path = '/static')








ALLOWED_EXTENSIONS = set(['png', 'jpg', 'jpeg'])


# UPLOAD  PICTURE FUNTIONS

# funtion to check if the uploaded file is in the  allowed file extenion list
def allowed_file(filename):
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS

# funtion that simply returns the file extenion 
def file_ext(filename):
    return str(filename.rsplit('.', 1)[1].lower()) 

# funtion prints the current time of buying in the format -- 'Saturday 17 October 2020'
def current_time():
    return str(datetime.now().strftime("%A %d %B %Y"))





















    
@buy_blueprint.route('/buy-user-details', methods=['GET', 'POST'])
@login_required
def buy_user_details():
    
    studentform = StudentForm()

    whatssapForm = WhatssapForm()

    addressform = AddressForm()
  
    user = current_user

    if current_user.is_student:
        abort(403)



    if  request.method == 'POST' and studentform.validate() :

        if studentform.is_student.data == "Yes" :
            user.is_student = True

        elif studentform.is_student.data == "No" :
            user.is_student = False

        db.session.commit()



    if request.method == 'POST' and whatssapForm.validate() :
        user.whatssap_number = whatssapForm.phone.data
        db.session.commit()


    if request.method == 'POST' and addressform.validate() :
        user.address = addressform.address.data
        db.session.commit()



        flash('INFORMATION ADDED!', 'success')
        return redirect(url_for('buy.ads', page = 1, sort = 'normal'))


            
    return render_template('buy/buy-user-details.html', whatssapForm = whatssapForm,  addressform = addressform, studentform = studentform, page_title = "please help us with the following info ", val = 'Proceed')






#main page with all the buys

@buy_blueprint.route('/ads',methods=['GET'])
@login_required  
def ads():
    page = request.args.get('page', 1, type = int)
    sort = request.args.get('sort')
    filtering  =  request.args.get('filtering')
    # posts = Post.query.paginate(page = page, per_page = 10  )



    ads = E_commerce.query.join(User).order_by(User.paid.desc()).order_by(E_commerce.date_of_post.desc()).paginate(page = page, per_page = 10  )

    posts = ads    

    sort_value = 'normal'

    filt = filtering



    if sort == 'normal':
        sort_value = 'normal'
        posts = ads

    elif sort == 'phone':
        print('entered this ablock')
        phones = E_commerce.query.filter_by(ad_type = 'phone').join(User).order_by(User.paid.desc()).order_by(E_commerce.date_of_post.desc()).paginate(page = page, per_page = 10  )
        posts = phones
        sort_value = 'phone'

    elif sort == 'tablet':
            print('entered this bblock')
            sort_value = 'tablet'
            tablets = E_commerce.query.filter_by(ad_type = 'tablet').join(User).order_by(User.paid.desc()).order_by(E_commerce.date_of_post.desc()).paginate(page = page, per_page = 10  )
            posts = tablets

























    if filtering == 'cheapest':
        print('entered this vlock')
        val = str(sort)
        print(val)
        posts = E_commerce.query.filter_by(ad_type = val).join(User).order_by(User.paid.desc()).order_by(E_commerce.price.asc()).paginate(page = page, per_page = 10  )
        
        sort_value = val
        filt = 'cheapest'


    if filtering == 'most_expensive':
        print('entered this clock')
        val = str(sort)
        print(val)
        posts = E_commerce.query.filter_by(ad_type = val).join(User).order_by(User.paid.desc()).order_by(E_commerce.price.desc()).paginate(page = page, per_page = 10  )
        
        sort_value = val
        filt = 'most_expensive'

    


    return render_template("buy/ads.html", sort_value = sort_value, page = page, posts = posts, filt = filt )
 





# route to view each buy individually
@buy_blueprint.route('/ad-view-page/<int:ad_id>/<string:ad_type>', methods=['GET', 'POST'])
@login_required  
def ad_view_page(ad_id, ad_type):

    commentForm = CommentForm()

    ad = E_commerce.query.get_or_404(ad_id)

    similar_ads = E_commerce.query.filter_by(ad_type = ad_type).order_by(E_commerce.date_of_post.asc()).limit(11)

        # logic for CONTENT field only
        # if request.method == 'POST' and commentForm.validate() :

        #     comment_body = commentForm.comment.data
        #     ad_id = ad_id

            # comment = Comments(
            #             comment_body = comment_body,
            #             buy_id = buy_id,
            #             commentor = current_user
            #             )

            # db.session.add(comment)
            # db.session.commit()
            # flash('COMMENT ADDED', 'success')
            # return redirect(request.url)


        # comments = Comments.query.filter_by(buy_id = buy_id).order_by(Comments.date_of_comment.desc()) 
        



    return render_template("buy/ad-view-page.html", ad = ad , similar_ads = similar_ads )








#the page that simulates online payment that gives you the ability to buy
@buy_blueprint.route('/buy-sturf-payment-page', methods=['GET', 'POST'])
@login_required  
def buy_payment_page():
    return render_template("buy/buy_sturf_payment.html")










#this route asks what kinda buy you want to make so it knows what kinda form to give you
@buy_blueprint.route('/ad-type', methods=['GET', 'POST'])
@login_required  
def ad_type():
    return render_template("buy/ad-type.html")










#the route that simulates the proceessing of  an online payment that gives you the ability to buy

@buy_blueprint.route('/buy-sturf-payment/<email>', methods=['GET', 'POST'])
@login_required  
def buy_sturf_payment(email):
    user = User.query.filter_by(email = email).first_or_404()
    user.paid = True
    user.generic = False
    db.session.commit()
    flash (' YOU HAVE BEEN SUBSCRIBED TO VIP, ENJOY!', 'success')
    return redirect(url_for('buy.buy', buy_type = 'normal'))





#the route that simulates the proceessing of  a free user, also gives you the ability to buy

@buy_blueprint.route('/buy-sturf-generic/<email>', methods=['GET', 'POST'])
@login_required  
def buy_sturf_generic(email):
    user = User.query.filter_by(email = email).first_or_404()
    user.generic = True
    user.paid = False
    db.session.commit()
    flash (' YOU HAVE BEEN REGISTERED AS A FREE USER', 'success')
    return redirect(url_for('buy.buy'))













@buy_blueprint.route('/user-template/<email>', methods=['GET'])
@login_required  
def user_template(email):

    user = User.query.filter_by(email = email).first_or_404()

    buy = buy.query.filter_by(author = user).order_by(buy.date_buyed.desc())

    buy_count = buy.query.filter_by(author = user).all()


    p = user.image_file
    img = url_for('static', filename = 'profile_pics/uploads/{}'.format(p))
    return render_template("buy/user-template.html", user = user, img = img, buy = buy,  buy_count= buy_count )






@buy_blueprint.route('/my-ads/<email>', methods=['GET'])
@login_required
def my_ads(email):

    user = User.query.filter_by(email = email).first_or_404()

    buy = buy.query.filter_by(author = user).order_by(buy.date_buyed.desc())

    buy_count = buy.query.filter_by(author = user).all()

    p = user.image_file
    img = url_for('static', filename = 'profile_pics/uploads/{}'.format(p))


    return render_template("buy/my-ads.html", user = user, img = img, buy = buy,  buy_count= buy_count )













# the route that renders the page to create phone ads
@buy_blueprint.route('/create-phone-ad/', methods=['GET', 'POST'])
@login_required
def create_phone_ad():
    #
    form = AdForm(CombinedMultiDict((request.files, request.form)))
    imagelist = []
    

    

    if  request.method == 'POST' and form.validate() :

        #the request.files object intance
        images = request.files.getlist('photo')

        for each in images:
            if not each:
                flash('NO  PHOTO CHOSEN', 'error')
                # print('block1 executed')
                return redirect(request.url)

            if each and allowed_file(each.filename) and each.filename != '':
                # print ('file---->',each.filename)

                split_file_name = os.path.splitext(each.filename)
                name_list = list(split_file_name)
                ex = str(file_ext(each.filename))
                secure = secure_filename(each.filename)

                #funtion to generate random name
                def random_name(filename):
                    random_hex = str(secrets.token_hex(8))
                #the return statement below returns a random name for each file with different parameters separated by underscores 
                    return   current_user.first_name + '_' + current_user.last_name + '_' + name_list[0] + '__' + random_hex + '__' + current_time() + '.' + ex


                #the name of the file gets assigned to the randomly generated file name 
                filename  = random_name(each.filename)
                # print(filename)

                uploads_path = os.path.join(current_app.root_path, 'static/buy_sturf', filename)

                #the next four lines just resizes the image to the given dimensions e.g 125 by 125

app/blueprints/help/views.py
from flask import Blueprint
from flask import render_template, request
from flask_security import login_required


help_blueprint = Blueprint('help', __name__, 
    static_folder='static', static_url_path = '/static')


@help_blueprint.route('/',methods=['GET'])
@login_required   
def index():
    return render_template("help/help.html")

app/templates/buy/create-phone-ad.html
{% from '_formhelpers.html' import render_field %}

<!DOCTYPE html>
<html lang = "en">
<head>
	<title>{{page_title}}</title>

	<link href="{{url_for('buy.static', filename='create-ad.css' )}}" rel="stylesheet" type="text/css" />

    <script src="{{url_for('static', filename='jquery-3.5.1.min.js' )}}"></script>

    <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='dropzone.min.css' )}}">


	<meta name="viewport" content = "width = device-width, initial-scale = 1" charset="utf-8" >

	<script type="text/javascript">

    function back(){
    	history.back();
    }
	
	</script>



</head> 





<body> 



<div id = "header">

<label for="check">
	<buttom  id="btn" type="button" onclick="back()";>&#10095;</button>
	
</label>


		
STURF

<div class="headtext">
	Improving your wellbeing <span class="dots">...</span>
</div>


</div>


{% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}

        <ul class=flashes>

        {% for category, message in messages %}

            <li class="{{ category }}">
                {{ message }}
            </li>

        {% endfor %}

        </ul>
        
    {% endif %}
{% endwith %}












<div class = "topicsentence">
		<center class = "pennyless"> 



            New mobile phone ad


				

				<br>
				<br>	
		</center>
</div>










<center>
        <div class="container">








                   <form method="POST" action =  "{{url_for('buy.create_phone_ad')}}" enctype="multipart/form-data">


                            <dl>
                                {{form.csrf_token}}
                            
                                {{ form.hidden_tag() }}


                                {{ render_field(form.photo) }}

                                
                                <br>
                                <br>
                                <br>
                                <br>
                                <br>
                                <br>
                                <br>
                                <br>


                                {{ render_field(form.title) }}
                                {{ render_field(form.brand) }}


                                <!-- product condition -->
                                <br>
                                <br>
                                <br>
                                <br>
                                <br>
                                <br>
                                <br>
                                <br>


                                {{form.condition.label}}

                                <br>


                                {% for subfield in form.condition %}

                                <tr>
                                <br>
                                <br>

                                <td>{{subfield}}</td>

                                <td>{{subfield.label}}</td> 



                                </tr>

                                {% endfor %}



                               <!-- price -->
                                <br>
                                <br>
                                <br>
                                <br>
                                <br>
                                <br>
                                <br>
                                <br>

                                {{ render_field(form.price) }}



                                <p>OPTIONAL</p>
                                <br>
                                <br>
                                <br>

                                {{ render_field(form.ram) }}
                                {{ render_field(form.screen_size) }}
                                {{ render_field(form.colour) }}
                                {{ render_field(form.camera) }}

                                <hr>


                                <br>
                                <br>

                                {{ render_field(form.description, cols="7", rows="7") }}


                               


                                
                            </dl>



                            <p><input type=submit value= "create Ad"  class="loginbutton"></p>
                           
                        </form>
                     



                   






                       
        </div>           
</center>




<script>
    $(function() {
        $("input[type = 'submit']").click(function(event) {
            var $fileUpload = $("input[type='file']");
            if (parseInt($fileUpload.get(0).files.length) > 5) {
                alert("YOU ARE ONLY ALLOWED TO UPLOAD A MAXIMUM of 5 PICTURES");
                event.preventDefault();
            }
        });
    });
</script>




<script src="{{url_for('static', filename='dropzone.min.js' )}}"></script>










<footer id = 'footer'>



<div class="footerians">
	<header><span style="margin-right: 5px; color: #ffffff; font-size: 25px;">☎</span>Get in touch with us</header>

	<ul>

	<li><a href="{{url_for('home.set_avatar', email = current_user.email, img = 'default2.jpg')}}"><div class="case1"></div></a></li>
	<li><a href="{{url_for('home.set_avatar', email = current_user.email, img = 'default2.jpg')}}"><div class="case2"></div></a></li>
	<li><a href="{{url_for('home.set_avatar', email = current_user.email, img = 'default2.jpg')}}"><div class="case3"></div></a></li>
	<li><a href="{{url_for('home.set_avatar', email = current_user.email, img = 'default2.jpg')}}"><div class="case4"></div></a></li>

	</ul>
	

</div>



<div class="t_and_t">
	<ul>
	<li><a href="{{url_for('home.set_avatar', email = current_user.email, img = 'default2.jpg')}}">Terms and conditions</a></li>
	<li><a href="{{url_for('home.set_avatar', email = current_user.email, img = 'default2.jpg')}}">what more can we do?</a></li>
	<li><a href="{{url_for('home.set_avatar', email = current_user.email, img = 'default2.jpg')}}">Ad policy</a></li>
	<li><a href="{{url_for('home.set_avatar', email = current_user.email, img = 'default2.jpg')}}">Content policy</a></li>
	</ul>
</div>


	

<div class="links">
	<ul>
	<li><a href="{{url_for('home.set_avatar', email = current_user.email, img = 'default2.jpg')}}">Home</a></li>
	<li><a href="file:///C:/Users/SIMON/Documents/site%20work/site/Electricity.html">Electricity</a></li>
	<li><a href="{{url_for('home.set_avatar', email = current_user.email, img = 'default2.jpg')}}">History</a></li>
	<li><a href="{{url_for('home.set_avatar', email = current_user.email, img = 'default2.jpg')}}">About Us</a></li>
	<li><a href="{{url_for('home.set_avatar', email = current_user.email, img = 'default2.jpg')}}">FAQS</a></li>
	<li><a href="{{url_for('security.logout')}}">logout</a></li>
	</ul>

</div>


	
<div class="copyright">
	Copyright &copy; 2020-2025 STURF
	All rights reserved.
	STURF is among the federally registered trademarks of
    STURF LLC and may not be used by third parties without explicit permission.


</div>





	
</footer>





</html>

app/templates/buy/followed-post.html
<!DOCTYPE html>
<html>

<head>

    <meta name="viewport" content = "width = device-width, initial-scale = 1" >

    <link href="{{url_for('post.static', filename='post-page.css' )}}" rel="stylesheet" type="text/css" />

    <title>Stay up to date unobstrusively </title>
    <script >
        function back(){
            history.back()
        }

    </script>

</head>













<body>

<!-- header section -->






<div id = "header">

    <label>
        <button  id="back" type="button" onclick="back()";>&#10094;</button>
    </label>


        
    <a class="header_link" href="{{url_for('home.general')}}">  
    STURF
    </a>


    <!----------- REPORT BUTTON ---------------->
    <input type="checkbox" id="check">

    <label for="check">
        <i  id="btn">&#10011;</i>
        <i  id="cancel">╳</i>
    </label>





    <div class="sidebar">

            

    <ul>







    {% if  current_user.generic or current_user.paid %}

        <li>
            <a  href="{{url_for('post.post_type')}}">

                <i style="font-style: normal;font-size: 30px; margin-right: 0px; ">&#9997;</i>

                 New Post

            </a>

        </li>

        {% else %}


        <li>
            <a  href="{{url_for('post.post_payment_page')}}">

                <i style="font-style: normal;font-size: 30px; margin-right: 0px; ">&#9997;</i>

                 I want to post

            </a>

        </li>

        
    {% endif %}



        <li>   
            <a  href="{{url_for('post.post')}}">

                <i style="font-style: normal;font-size: 30px; margin-right: 0px; ">&#9997;</i>

                 Explore

            </a>

        </li>




        <li>    
            <a  href="{{url_for('post.followed_post')}}">

                <i style="font-style: normal;font-size: 30px; margin-right: 0px; ">&#9997;</i>

                 Followed

            </a>

        </li>






        


    <li>
        <a style="color: gold;" href="{{url_for('post.post_payment_page')}}">

            <i style="font-style: normal;font-size: 30px; margin-right: 0px; color: gold;">&starf;</i>

        VIP

        </a>

    </li>



    <li>
        <a href="{{url_for('help.index')}}">
            <i style="font-style: normal;">&#10067;</i>

        Help 

        </a>

    </li>


    </ul>
            
            

    </div>

<!----------- END OF REPORT BUTTON ---------------->







    <div id="headtext">
        Improving your wellbeing <span class="dots">...</span>
    </div>


</div>







{% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}

        <ul class=flashes>

        {% for category, message in messages %}
            <center>

            <li class="{{ category }}">
                {{ message }}
            </li>

            </center>
        {% endfor %}

        </ul>
        
    {% endif %}
{% endwith %}










<!-- <center > 
<div id = "linkcontainer">

    <div>
        <center>
    <div class = "login">
        
        <a class = "loginbutton" href="#">
            <center>explore</center>
        </a>
        </center>       
    </div>
    </div>
</div>
</div>
</center>




<center > 
<div id = "linkcontainer">

    <div>
        <center>
    <div class = "login">
        
        <a class = "loginbutton" href="#">
            <center>followed</center>
        </a>
        </center>       
    </div>
    </div>
</div>
</div>
</center>
 -->











































        {%if page < 2 %}






                {% if post_value == 'normal'  %}






                <div class = "topicsentence" >


                       
                               Explore posts by everyone
                            
                                <br>
                                <br>    
                        
                </div>


                {% else %}






                <div class = "topicsentence" >

                        
                       
                               Users you're following
                            
                                <br>
                                <br>    
                        
                </div>

                {% endif %}




        {% else %}


                                <br>
                                <br>
                                <br>

        <!-- do nothing -->


        {% endif %}




























<p class="users_count">

<span style='color: #79ff4d; font-size: 17px; font-weight: bold; font-family: "Comic Sans MS", cursive, sans-serif;
'> 90 </span> % of all our users visited this page today

</p>



<p class="users_count">

<span style='color: #79ff4d; font-size: 17px; font-weight: bold; font-family: "Comic Sans MS", cursive, sans-serif;
'> {{ posts.total }} </span> 



    {% if posts.total > 1  %}

            posts

    {% else %}

            post

    {% endif %}




  in total

</p>





</div>

  






        




{% if posts.total >= 1  %}

  

        {% for post in posts.items %}
        <!-- <div class="individual-post"> -->
              
        <div class="wrap">

                                

                                                <a  href="{{url_for('post.post_view_page', post_id = post.id )}}">
                        <div class="img"  >

                                                    <h1 class="chk" style="font-size: 17px;  ">view</h1>
                                                </a>
                                                    
                                                    <i style="
                                                    position: absolute;
                                                    z-index: 1;
                                                    padding:5px;
                                                    padding-top: 0px;
                                                    font-size: 20px;
                                                    font-style: normal;
                                                    color: #79ff4d;
                                                    text-shadow: 2px 3px 2px #000000;
                                                    ">


                                                    {% if  post.is_event %}

                                                    &#9873; 

                                                    {% else %}

                                                    &#10148;
                                                    

                                                    {% endif %}

                                                    

                                                    </i>


                                                    
                                                    <img src="{{url_for('static', filename='post_sturf/' + post.image_file )}}" alt="{{post.author.first_name}}" width="300" height="200">
                                                   

                                                    <h1>

                                                        {% if post.title.__len__() >= 15  %}

                                                        {{ post.title[0:15].upper() }}...

                                                        {% else %}

                                                        {{ post.title.upper()}}

                                                        {% endif %}

                                                    </h1>



                                                    <div class="desc">

                                                        {% if post.content.__len__() >= 20  %}

                                                        {{ post.content[0:20] }}...

                                                        {% else %}

                                                        {{ post.content}}

                                                        {% endif %}

                                                    </div>



                                                    <p>

                                                    <span style="color: green; ">by:</span>

                                                    {{post.author.first_name}} 

                                                    </p>
                                                    
                                                    <p>

                                                    <span style="color: green;">on:</span>

                                                    {{post.date_posted.strftime("%a %d %B, %Y")}}

                                                    </p>
                        </div>
                    
             

    </div>              
        {%endfor%}





{% else %}





<center>
    <i style="
    padding:5px;
    padding-top: 0px;
    font-size: 70px;
    font-style: normal;
    color: #79ff4d;
    text-shadow: 2px 3px  black;
    font-weight: bold
    ">


    &#9925;



    </i>

    <h1 class="damn">
    Damn!....no posts? well don't just stare, do something about it will ya?
    </h1>

</center>







{% endif %}
    
    
</body>







<script>
function openCity(evt, cityName) {


    var i, tabcontent, tablinks;
    tabcontent = document.getElementsByClassName("tabcontent");
    for (i = 0; i < tabcontent.length; i++) {
        tabcontent[i].style.display = "none";
    }



    tablinks = document.getElementsByClassName("tablinks");
    for (i = 0; i < tablinks.length; i++) {
        tablinks[i].className = tablinks[i].className.replace(" active", "");
    }
    document.getElementById(cityName).style.display = "block";
    evt.currentTarget.className += " active";
}
</script>






<center>
    <div class="pagination"> 
    {% for page_num in posts.iter_pages(left_edge=1, right_edge = 1, left_current = 1, right_current = 2) %}


        {%if page_num %}


            

                    {%if posts.page == page_num%}
                    <a  class="pagination_highlight" href="{{url_for('post.followed_post', page = page_num, post_type = 'followed')}}">{{page_num}}</a>

                    {% else %}

                     <a  class="pagination_normal" href="{{url_for('post.followed_post', page = page_num, post_type = 'followed')}}">{{page_num}}</a>
                    {% endif %}

            



        {% else %}

        ...


        {% endif %}



    {% endfor %}
    </div>
</center>







<!-- ..............................footer............................ -->

<footer id = 'footer' style="margin-top: 10%">



<div class="footerians">
    <header><span style="margin-right: 5px; color: #ffffff; font-size: 25px;">☎</span>Get in touch with us</header>

    <ul>

    <li><a href="#"><div class="case1"></div></a></li>
    <li><a href="#"><div class="case2"></div></a></li>
    <li><a href="#"><div class="case3"></div></a></li>
    <li><a href="#"><div class="case4"></div></a></li>

    </ul>
    

</div>



<div class="t_and_t">
    <ul>
    <li><a href="#">Terms and conditions</a></li>
    <li><a href="#">what more can we do?</a></li>
    <li><a href="#">Ad policy</a></li>
    <li><a href="#">Content policy</a></li>
    </ul>
</div>


    

<div id="links">
    <ul>
    <li><a href="#">Home</a></li>
    <li><a href="file:///C:/Users/SIMON/Documents/site%20work/site/Electricity.html">Electricity</a></li>
    <li><a href="#">History</a></li>
    <li><a href="#">About Us</a></li>
    <li><a href="#">FAQS</a></li>
    <li><a href="#">logout</a></li>
    </ul>

</div>


    
<div class="copyright">
    Copyright &copy; 2020-2025 STURF
    All rights reserved.
    STURF is among the federally registered trademarks of
    STURF LLC and may not be used by third parties without explicit permission.


</div>





    
</footer>


</html>




	